services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tbo\TboThemeBundle\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/ContaoManager/"
            - "../src/TboThemeBundle.php"

    Tbo\TboThemeBundle\Twig\TboExtension:
        tags: ["twig.extension"]

    Tbo\TboThemeBundle\EventListener\DataContainer\SettingsFontListener:
        public: true
        arguments:
            $projectDir: "%kernel.project_dir%"
            $contaoCoreLogger: "@monolog.logger.contao.error"